// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFDtnZNTvq7HvNfuw941z3MlphwwJLR00',
    appId: '1:646933084960:web:3fc1674572ee45804f3545',
    messagingSenderId: '646933084960',
    projectId: 'blog-app-flutter-5d51e',
    authDomain: 'blog-app-flutter-5d51e.firebaseapp.com',
    storageBucket: 'blog-app-flutter-5d51e.firebasestorage.app',
    measurementId: 'G-31N6R9ELRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcPEHW6h9kGqAfciCiWBTakyDLI7E_X_c',
    appId: '1:646933084960:android:3946afa3972a01354f3545',
    messagingSenderId: '646933084960',
    projectId: 'blog-app-flutter-5d51e',
    storageBucket: 'blog-app-flutter-5d51e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjoZZ7VxouBoXW68Lw7fU3ZJbweKnUoL8',
    appId: '1:646933084960:ios:41c9d2707ba356244f3545',
    messagingSenderId: '646933084960',
    projectId: 'blog-app-flutter-5d51e',
    storageBucket: 'blog-app-flutter-5d51e.firebasestorage.app',
    iosBundleId: 'com.example.blogapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjoZZ7VxouBoXW68Lw7fU3ZJbweKnUoL8',
    appId: '1:646933084960:ios:41c9d2707ba356244f3545',
    messagingSenderId: '646933084960',
    projectId: 'blog-app-flutter-5d51e',
    storageBucket: 'blog-app-flutter-5d51e.firebasestorage.app',
    iosBundleId: 'com.example.blogapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFDtnZNTvq7HvNfuw941z3MlphwwJLR00',
    appId: '1:646933084960:web:72b9b11c97f99e3e4f3545',
    messagingSenderId: '646933084960',
    projectId: 'blog-app-flutter-5d51e',
    authDomain: 'blog-app-flutter-5d51e.firebaseapp.com',
    storageBucket: 'blog-app-flutter-5d51e.firebasestorage.app',
    measurementId: 'G-1Q4FL01MJ6',
  );
}
